Description: >
    This template deploys two different Amazon Kinesis Streams we need for the architecture.
Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
    KinesisShardsNumber: 
        Description: "Select the number of shards"
        Type: Number
Resources:
  KinesisRT:
    Type: 'AWS::Kinesis::Stream'
    Properties:
      Name: !Sub ${EnvironmentName}-KinesisRT
      RetentionPeriodHours: 24
      ShardCount: 
        !Ref KinesisShardsNumber
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-RealTime


Outputs:

  KinesisRT:
    Description: A reference to the Kinesis Stream containing all events from reactive application.
    Value: !Ref KinesisRT

